### ISSUE TITLE
Module not found errors after updating to 0.14 (babel/runtime)

### ISSUE THREAD

**Issue by apaatsio** [n6g7/redux-saga-firebase#130]
After updating to 0.14 I'm getting errors about missing `@babel/runtime`. Version 0.13 works fine.

Quick fix is to install babel/runtime: `npm i @babel/runtime`.

I believe the proper fix would be to add `@babel/runtime` to the dependencies of `redux-saga-firebase`.

```
./node_modules/redux-saga-firebase/dist/functions.js
Module not found: Can't resolve '@babel/runtime/core-js/object/keys' in '/path/to/project/node_modules/redux-saga-firebase/dist'
./node_modules/redux-saga-firebase/dist/index.js
Module not found: Can't resolve '@babel/runtime/helpers/classCallCheck' in '/path/to/project/node_modules/redux-saga-firebase/dist'
./node_modules/redux-saga-firebase/dist/index.js
Module not found: Can't resolve '@babel/runtime/helpers/createClass' in '/path/to/project/node_modules/redux-saga-firebase/dist'
./node_modules/redux-saga-firebase/dist/database.js
Module not found: Can't resolve '@babel/runtime/helpers/interopRequireDefault' in '/path/to/project/node_modules/redux-saga-firebase/dist'
[...]
```

**Comment by hoffmanc** [comment]
I'm running into this error as well, but the `npm i @babel/runtime` workaround doesn't work for me: after installing I get

```
ERROR in dll reactBoilerplateDeps
Module not found: Error: Can't resolve '@babel/runtime' in '/myapp'
```

**Comment by n6g7** [comment]
Hey guys, sorry about this. `@babel/runtime` is already in the devDependencies but we might need to add it to the regular dependencies.
I'll look into this soon.

**Comment by hoffmanc** [comment]
well I just went with 0.13, and that seems to be working.

**Comment by apaatsio** [comment]
I updated to `@babel/runtime@7.0.0-beta.56` and I started getting the same errors again. Downgrading back to `7.0.0-beta.55` helped.

**Comment by n6g7** [comment]
Trying to reproduce:

- rsf 0.14.0
- babel:
  - 7.0.0-beta.51 ✅
  - 7.0.0-beta.52 ✅
  - 7.0.0-beta.53 ✅
  - 7.0.0-beta.54 ✅
  - 7.0.0-beta.55 ❓
  - 7.0.0-beta.56 ❓

**Comment by n6g7** [comment]
@apaatsio @hoffmanc I released a potential fix as `v0.14.1-alpha.1`. Before I merge in master and make a new release, can you please confirm that this fixes it for you too?

To upgrade: `yarn upgrade redux-saga-firebase@next`

**Comment by apaatsio** [comment]
`v0.14.1-alpha.1` did not fix it for me. I'm still getting the same errors. I don't see `@babel/runtime` installed under `node_modules` either.

My project is created with `create-react-app` and therefore I have babel 6 installed, including `babel-runtime@6.26.0`. I'm wondering if that interferes somehow with babel 7.

**Comment by n6g7** [comment]
@apaatsio Thanks for the feedback!

> My project is created with create-react-app and therefore I have babel 6 installed, including babel-runtime@6.26.0. I'm wondering if that interferes somehow with babel 7.

Probably. I only updated babel to v7-beta.56 in v0.14.1-alpha.1 and that fixed it for me. Now next step is to install @babel/runtime in dependencies. I'll release a second alpha and let you know when that's ready. :)

Thanks for your patience!

**Comment by apaatsio** [comment]
Here's a minimal repo to reproduce the issue: https://github.com/apaatsio/rsf-issue-130

Just run `yarn install` & `yarn start`.

**Comment by apaatsio** [comment]
`v0.14.1-alpha.2` works for me, thank you! Great job :+1:

**Comment by n6g7** [comment]
Cool! I'll release later today.

**Comment by n6g7** [comment]
@apaatsio @hoffmanc: I just released [v0.14.1](https://github.com/n6g7/redux-saga-firebase/releases/tag/v0.14.1) with the fix. You can upgrade with `yarn upgrade redux-saga-firebase`. 😉

Thanks for being patient. :)

I'm closing this for now, let me know if the problem resurfaces.
